### PR TITLE
feature: get the doctoral degree

### PR DESCRIPTION
**Pull request by monperrus**
per the defense of today,  what about giving Benjamin the doctoral degree?

@bbaudry @seintur @vmassol @ldubousq @jcabot WDYT?

@danielleberre, president of the committee,  merge?

### CODE REVIEW

**Comment by bbaudry** [comment]
LGTM

**Comment by seintur** [comment]
LGTM too

**Comment by vmassol** [comment]
+1 Well done Benjamin!

**Comment by danielleberre** [comment]
good for me

**Pull request merged**
